[package]
name = "governance"
description = "A flexible monolithic governance contract, developed for use with Carmine Options AMM"
version = "0.2.0"
cairo-version = "2.3.1"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
cubit = { git = "https://github.com/akhercha/cubit.git", branch = "chore/cairo_upgrade" }
starknet = ">=1.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", commit = "acdd4a573cf6a89647f48124e75074674f844f47"}

[[target.starknet-contract]]
casm = true

[[tool.snforge.fork]]
name = "MAINNET"
url = "http://34.22.208.73:6060/"
block_id.tag = "Latest"

[[tool.snforge.fork]]
name = "GOERLI"
url = "https://limited-rpc.nethermind.io/goerli-juno"
block_id.tag = "Latest"

